// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yloegxgxnghnlqzmlbei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlsb2VneGd4bmdobmxxem1sYmVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDg1NjgsImV4cCI6MjA3Mzg4NDU2OH0.l3xjRBPZ0qliK2YmrU5_kgR-v5JPWEFPmdDOqupWQaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});